from __future__ import annotations

import pandas as pd


SAMPLE_MOVERS = [
    {
        "ticker": "SERA",
        "company_name": "Sera Prognostics Inc.",
        "latest_price": 8.72,
        "previous_close": 4.98,
        "premarket_volume": 8_420_000,
        "relative_volume": 16.8,
        "market_cap": 342_000_000,
        "float_shares": 18_200_000,
        "headline": "Sera Prognostics announces FDA approval for expanded testing platform",
        "summary": "The company said regulators approved expanded use of its diagnostic platform.",
        "premarket_high": 9.18,
        "premarket_low": 6.95,
        "vwap": 8.21,
        "bid": 8.69,
        "ask": 8.74,
    },
    {
        "ticker": "LUMN",
        "company_name": "Lumen Technologies Inc.",
        "latest_price": 5.45,
        "previous_close": 4.29,
        "premarket_volume": 12_100_000,
        "relative_volume": 9.4,
        "market_cap": 5_520_000_000,
        "float_shares": 978_000_000,
        "headline": "Lumen raises guidance after earnings beat",
        "summary": "Management cited stronger enterprise demand and cost controls.",
        "premarket_high": 5.62,
        "premarket_low": 4.93,
        "vwap": 5.31,
        "bid": 5.44,
        "ask": 5.47,
    },
    {
        "ticker": "ARQQ",
        "company_name": "Arqit Quantum Inc.",
        "latest_price": 2.91,
        "previous_close": 2.05,
        "premarket_volume": 3_640_000,
        "relative_volume": 12.1,
        "market_cap": 186_000_000,
        "float_shares": 27_300_000,
        "headline": "Arqit signs strategic partnership with named defense customer",
        "summary": "The partnership covers a product launch for secure network technology.",
        "premarket_high": 3.05,
        "premarket_low": 2.45,
        "vwap": 2.82,
        "bid": 2.9,
        "ask": 2.95,
    },
    {
        "ticker": "MOBX",
        "company_name": "Mobix Labs Inc.",
        "latest_price": 1.64,
        "previous_close": 1.22,
        "premarket_volume": 911_000,
        "relative_volume": 6.3,
        "market_cap": 72_000_000,
        "float_shares": 9_600_000,
        "headline": "Mobix Labs announces patent for wireless semiconductor design",
        "summary": "The company says the patent supports future product development.",
        "premarket_high": 1.78,
        "premarket_low": 1.42,
        "vwap": 1.59,
        "bid": 1.61,
        "ask": 1.68,
    },
    {
        "ticker": "HOLO",
        "company_name": "MicroCloud Hologram Inc.",
        "latest_price": 1.08,
        "previous_close": 0.74,
        "premarket_volume": 2_280_000,
        "relative_volume": 8.9,
        "market_cap": 31_000_000,
        "float_shares": 6_400_000,
        "headline": "MicroCloud Hologram highlights AI and blockchain technology roadmap",
        "summary": "The update did not include a named customer or confirmed contract.",
        "premarket_high": 1.19,
        "premarket_low": 0.91,
        "vwap": 1.04,
        "bid": 1.04,
        "ask": 1.11,
    },
    {
        "ticker": "BBAI",
        "company_name": "BigBear.ai Holdings Inc.",
        "latest_price": 3.88,
        "previous_close": 3.31,
        "premarket_volume": 1_420_000,
        "relative_volume": 4.1,
        "market_cap": 985_000_000,
        "float_shares": 104_000_000,
        "headline": None,
        "summary": None,
        "premarket_high": 3.96,
        "premarket_low": 3.57,
        "vwap": 3.79,
        "bid": 3.86,
        "ask": 3.91,
    },
    {
        "ticker": "APTO",
        "company_name": "Aptose Biosciences Inc.",
        "latest_price": 0.86,
        "previous_close": 0.68,
        "premarket_volume": 78_000,
        "relative_volume": 2.7,
        "market_cap": 19_000_000,
        "float_shares": 14_100_000,
        "headline": "Aptose announces registered direct offering",
        "summary": "The company expects to use proceeds for working capital.",
        "premarket_high": 0.94,
        "premarket_low": 0.8,
        "vwap": 0.87,
        "bid": 0.82,
        "ask": 0.91,
    },
]


def load_sample_movers() -> pd.DataFrame:
    return pd.DataFrame(SAMPLE_MOVERS)
